### ISSUE TITLE
Inconsistent sfc-name="BaseTransition" behavior

### ISSUE THREAD

**Issue by Flapperoo** [ciderapp/cider-themekit#1]
On startup or viewing for the first-time, sfc-name="BaseTransition" get applied then removed at second load.

See example: 
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/f3b36877-089a-4df8-95d7-41fad124b209)
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/ff9b7ea6-824f-4f8d-9861-6e78f2d7baac)

First expansion item (Apple Music) has been closed and expanded, sfc-name="BaseTransition" disappeared.
Second expansion item (Library) is the startup state, sfc-name="BaseTransition" is present.
Closing the expansion item results in the sfc-name disappearing.

---

This is also present in Settings, see example:
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/750c70f2-8082-461b-989d-def580f89084)
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/e9f81183-c6b4-41a6-b6f7-62f612e77646)

Clicking to visual and reloading the general settings page results in sfc-name="BaseTransition" disappearing:
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/79912519-3e80-423b-b232-1bcb31477b49)
![image](https://github.com/ciderapp/cider-themekit/assets/22081694/bdee8e7a-bcbf-42fb-87fd-f6f0438d5bbf)

---

Am I misusing the BaseTransition sfc-name or is there a reason this behavior is like this?

**Comment by booploops** [comment]
Hi, I'd suggest not generally targeting [sfc-name=BaseTransition] because that is something Vue makes with `<Transition>` internally.

We can put some specifically targetable classes or attributes on the elements that have it if you would like and give us where the exact elements are

**Comment by Flapperoo** [comment]
I see, thanks for the response. 

There looks to be good enough coverage in the entire application as far as I am aware, just some oddities in regards to some select boxes not inheriting the `c-select` class so I had to target `data-v-c081d946` (currently seeing this in `Songs` > `Library Options` > `Item Size`) as well.

Otherwise, everything can be worked around on.
